// Class AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary
// Size: 0x28 (Inherited: 0x28)
struct UAnalyticsBlueprintLibrary : UBlueprintFunctionLibrary {

	bool StartSessionWithAttributes(struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.StartSessionWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b6e04
	bool StartSession(); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.StartSession // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6de0
	void SetUserId(struct FString UserId); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetUserId // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6d48
	void SetSessionId(struct FString SessionId); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetSessionId // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6cb0
	void SetLocation(struct FString Location); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetLocation // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6c18
	void SetGender(struct FString Gender); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetGender // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6b80
	void SetBuildInfo(struct FString BuildInfo); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetBuildInfo // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6ae8
	void SetAge(int32_t Age); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.SetAge // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6a64
	void RecordSimpleItemPurchaseWithAttributes(struct FString ItemId, int32_t ItemQuantity, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordSimpleItemPurchaseWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b6904
	void RecordSimpleItemPurchase(struct FString ItemId, int32_t ItemQuantity); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordSimpleItemPurchase // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6810
	void RecordSimpleCurrencyPurchaseWithAttributes(struct FString GameCurrencyType, int32_t GameCurrencyAmount, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordSimpleCurrencyPurchaseWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b66b0
	void RecordSimpleCurrencyPurchase(struct FString GameCurrencyType, int32_t GameCurrencyAmount); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordSimpleCurrencyPurchase // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b65bc
	void RecordProgressWithFullHierarchyAndAttributes(struct FString ProgressType, struct TArray<struct FString> ProgressNames, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordProgressWithFullHierarchyAndAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b6434
	void RecordProgressWithAttributes(struct FString ProgressType, struct FString ProgressName, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordProgressWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b62c0
	void RecordProgress(struct FString ProgressType, struct FString ProgressName); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordProgress // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b61b4
	void RecordItemPurchase(struct FString ItemId, struct FString Currency, int32_t PerItemCost, int32_t ItemQuantity); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordItemPurchase // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b6008
	void RecordEventWithAttributes(struct FString EventName, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordEventWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b5ef4
	void RecordEventWithAttribute(struct FString EventName, struct FString AttributeName, struct FString AttributeValue); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordEventWithAttribute // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5d80
	void RecordEvent(struct FString EventName); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordEvent // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5ce8
	void RecordErrorWithAttributes(struct FString Error, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordErrorWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b5bd4
	void RecordError(struct FString Error); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordError // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5b3c
	void RecordCurrencyPurchase(struct FString GameCurrencyType, int32_t GameCurrencyAmount, struct FString RealCurrencyType, float RealMoneyCost, struct FString PaymentProvider); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordCurrencyPurchase // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b591c
	void RecordCurrencyGivenWithAttributes(struct FString GameCurrencyType, int32_t GameCurrencyAmount, struct TArray<struct FAnalyticsEventAttr> Attributes); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordCurrencyGivenWithAttributes // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x64b57bc
	void RecordCurrencyGiven(struct FString GameCurrencyType, int32_t GameCurrencyAmount); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.RecordCurrencyGiven // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b56c8
	struct FAnalyticsEventAttr MakeEventAttribute(struct FString AttributeName, struct FString AttributeValue); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.MakeEventAttribute // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x64b5580
	struct FString GetUserId(); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.GetUserId // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b550c
	struct FString GetSessionId(); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.GetSessionId // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5498
	void FlushEvents(); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.FlushEvents // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5484
	void EndSession(); // Function AnalyticsBlueprintLibrary.AnalyticsBlueprintLibrary.EndSession // (Final|Native|Static|Public|BlueprintCallable) // @ game+0x64b5470
};

