// AnimBlueprintGeneratedClass ItemAnimLayerInterface.ItemAnimLayerInterface_C
// Size: 0x28 (Inherited: 0x28)
struct UItemAnimLayerInterface_C : UAnimLayerInterface {

	void ItemPreIK(struct FPoseLink InPose_PreIK, struct FPoseLink ItemPreIK); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemPreIK // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFullBodyOverride(struct FPoseLink InPoseFullBody, struct FPoseLink ItemFullBodyOverride); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFullBodyOverride // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemAimOffset(struct FPoseLink InPose_AimOffset, float AimOffsetAlpha, float Yaw, float Pitch, struct FPoseLink InPose_UpperLowerPreMeleeAO, struct FPoseLink ItemAimOffset); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemAimOffset // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSkeletalControl(struct FPoseLink InPose, struct FPoseLink ItemSkeletalControl); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSkeletalControl // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSwimJumpSurfaceEnd(struct FPoseLink ItemSwimJumpSurfaceEnd); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSwimJumpSurfaceEnd // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSwimJumpSurfaceLoop(struct FPoseLink ItemSwimJumpSurfaceLoop); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSwimJumpSurfaceLoop // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSwimJumpFallLoop(struct FPoseLink ItemSwimJumpFallLoop); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSwimJumpFallLoop // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSwimJumpStartLoop(struct FPoseLink ItemSwimJumpStartLoop); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSwimJumpStartLoop // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSwimJumpStart(struct FPoseLink ItemSwimJumpStart); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSwimJumpStart // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemRelaxedEntry(struct FPoseLink InPoseRelaxedEntry, struct FPoseLink ItemRelaxedEntry); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemRelaxedEntry // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyJogPostPivot(struct FPoseLink InPoseLowerBodyJogPostPivot, struct FPoseLink ItemLowerBodyJogPostPivot); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyJogPostPivot // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyJogPrePivot(struct FPoseLink InPoseLowerBodyJogPrePivot, struct FPoseLink ItemLowerBodyJogPrePivot); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyJogPrePivot // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyJogStop(struct FPoseLink InPoseLowerBodyJogStop, struct FPoseLink ItemLowerBodyJogStop); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyJogStop // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyJogStart(struct FPoseLink InPoseLowerBodyJogStart, struct FPoseLink ItemLowerBodyJogStart); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyJogStart // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyLeanAdditive(struct FPoseLink InPoseLowerBodyLeanAdditive, struct FPoseLink ItemLowerBodyLeanAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyLeanAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemLowerBodyMovement(struct FPoseLink InPoseLowerBodyMovement, struct FPoseLink ItemLowerBodyMovement); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemLowerBodyMovement // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJogPostPivotAdditive(struct FPoseLink InPosePostPivotAdditive, struct FPoseLink ItemJogPostPivotAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJogPostPivotAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJogPrePivotAdditive(struct FPoseLink InPosePrePivotAdditive, struct FPoseLink ItemJogPrePivotAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJogPrePivotAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJogStopAdditive(struct FPoseLink InPoseJogStopAdditive, struct FPoseLink ItemJogStopAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJogStopAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJogStartAdditive(struct FPoseLink InPoseJogStartAdditive, struct FPoseLink ItemJogStartAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJogStartAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFlyModeLoopAdditive(struct FPoseLink ItemFlyModeLoopAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFlyModeLoopAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFlyModeStartAdditive(struct FPoseLink ItemFlyModeStartAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFlyModeStartAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemZipLineStartAdditive(struct FPoseLink ItemZipLineStartAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemZipLineStartAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJetPackJumpAdditive(struct FPoseLink ItemJetPackJumpAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJetPackJumpAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJetPackStartAdditive(struct FPoseLink ItemJetPackStartAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJetPackStartAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFallLandAdditive(struct FPoseLink ItemFallLandAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFallLandAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFallAdditive(struct FPoseLink ItemFallAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFallAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJumpLoopAdditive(struct FPoseLink ItemJumpLoopAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJumpLoopAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemJumpUpAdditive(struct FPoseLink ItemJumpUpAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemJumpUpAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemSlopeSliding(struct FPoseLink ItemSlopeSliding); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemSlopeSliding // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemCrouchTurningAdditive(struct FPoseLink ItemCrouchTurningAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemCrouchTurningAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemIdleAdditive(struct FPoseLink InPoseIdleAdditive, struct FPoseLink ItemIdleAdditive); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemIdleAdditive // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemFullBodySprint(struct FPoseLink InPoseSprint, struct FPoseLink ItemFullBodySprint); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemFullBodySprint // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void ItemUpperBody(struct FPoseLink InPoseUpperBody, struct FFortAnimInput_AdjustedAim InputParam, struct FPoseLink ItemUpperBody); // Function ItemAnimLayerInterface.ItemAnimLayerInterface_C.ItemUpperBody // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
};

