// BlueprintGeneratedClass StyleLibrary.StyleLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UStyleLibrary_C : UBlueprintFunctionLibrary {

	void Get Conning Color From Homebase Rating(int32_t HomeBaseRating, int32_t DifficultyLevel, struct UObject* __WorldContext, struct FLinearColor DifficultyColor); // Function StyleLibrary.StyleLibrary_C.Get Conning Color From Homebase Rating // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Conning Color For Specific Difficulty(int32_t Difficulty Value, struct UObject* __WorldContext, struct FLinearColor Difficulty Linear Color, bool Invalid); // Function StyleLibrary.StyleLibrary_C.Get Conning Color For Specific Difficulty // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Conning Color From Difficulty Value(int32_t Player Account Level, float Content Difficulty Level, struct UObject* __WorldContext, struct FLinearColor Difficulty Linear Color, bool Success, struct FText ToolTipText, int32_t DifficultyValue); // Function StyleLibrary.StyleLibrary_C.Get Conning Color From Difficulty Value // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get HarvestWeakPoint Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor StyleSheetOut); // Function StyleLibrary.StyleLibrary_C.Get HarvestWeakPoint Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void ResizeBrush(enum class EFortBrushSize BrushSize, struct FSlateBrush BaseBrush, struct UObject* __WorldContext, struct FSlateBrush ResizedBrush); // Function StyleLibrary.StyleLibrary_C.ResizeBrush // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Base & Buff Colors(enum class EFortStatValueDisplayType Display Type, enum class EFortBuffState Buff State, struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Base, struct FLinearColor Buff); // Function StyleLibrary.StyleLibrary_C.Get Base & Buff Colors // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Bolt Elemental Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Bolt Elemental Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Ice Elemental Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Ice Elemental Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Fire Elemental Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Fire Elemental Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Unique Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Unique Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Item Size(struct FFortUIStylesheet StyleSheet, enum class EFortBrushSize Brush Size, struct UObject* __WorldContext, struct FVector2D Item Size); // Function StyleLibrary.StyleLibrary_C.Get Item Size // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Debuff Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Debuff Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Buff Color(struct FFortUIStylesheet StyleSheet, struct UObject* __WorldContext, struct FLinearColor Color); // Function StyleLibrary.StyleLibrary_C.Get Buff Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Item Icon Size(struct FFortUIStylesheet StyleSheet, enum class EFortBrushSize Brush Size, struct UObject* __WorldContext, struct FVector2D Icon Size); // Function StyleLibrary.StyleLibrary_C.Get Item Icon Size // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Standard Icon Size(struct FFortUIStylesheet StyleSheet, enum class EFortBrushSize Brush Size, struct UObject* __WorldContext, struct FVector2D Icon Size); // Function StyleLibrary.StyleLibrary_C.Get Standard Icon Size // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void Get Theme(struct FFortUIStylesheet StyleSheet, enum class EFortUITheme Theme Type, struct UObject* __WorldContext, struct FFortUITheme Theme); // Function StyleLibrary.StyleLibrary_C.Get Theme // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
	void Get Theme Color(struct FFortUIStylesheet StyleSheet, enum class EFortUITheme Theme Type, enum class EFortUIThemeColor Color Type, struct UObject* __WorldContext, struct FLinearColor Theme Color); // Function StyleLibrary.StyleLibrary_C.Get Theme Color // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xda7c34
};

