// AnimBlueprintGeneratedClass SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C
// Size: 0x28 (Inherited: 0x28)
struct USwimmingAnimLayerInterface_C : UAnimLayerInterface {

	void SwimmingDiveJumpingLayer(struct FPoseLink PassThroughSwimmingDiveJumping, bool IsHidingInPropLayer2, float MainInstanceDiveJumpLayerAlpha, enum class EFortPlayerAnimBodyType AnimBodyTypePassThrough, struct FPoseLink SwimmingDiveJumpingLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingDiveJumpingLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingFullBodyAdditiveLayer(struct FPoseLink PassThroughFullBodyAdditive, struct FPoseLink SwimmingFullBodyAdditiveLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingFullBodyAdditiveLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingAdditiveLayer(struct FPoseLink IdleAdditive Cache, struct FPoseLink MovementAdditiveLayerPose Cache, struct FPoseLink FullBody, float PlayMeleeAttackAOLayer, float DisableArmsHeadAdditiveCurveAlphaLayer, float DisableIKRootAdditiveCurveAlphaLayer, float LocomotionAdditiveAlphaLayer, float MainInstanceAdditiveLayerAlpha, struct FPoseLink UpperAndLowerBody Cache, struct FPoseLink SprintingPose_PostMask_Cache, struct FPoseLink SwimmingAdditiveLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingAdditiveLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingLowerBodyLayer(struct FPoseLink UpperBody Cache, struct FPoseLink PreUpperBodySlot Cache, struct FPoseLink PassThroughSwimmingLowerBody, struct FPoseLink SwimmingLowerBodyLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingLowerBodyLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingUpperBodyPoseNonTargetingLayer(struct FPoseLink PassThroughSwimmingUpperBodyPoseNonTargeting, struct FPoseLink SwimmingUpperBodyPoseNonTargetingLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingUpperBodyPoseNonTargetingLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingUpperBodyPoseTargetingLayer(struct FPoseLink PassThroughSwimmingUpperBodyPoseTargeting, struct FPoseLink SwimmingUpperBodyPoseTargetingLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingUpperBodyPoseTargetingLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingSprintLayer(struct FPoseLink PassThroughSwimmingSprint, bool IsHidingInPropLayer, struct FPoseLink SwimmingSprintLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingSprintLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingMovementAdditiveLayerPose(struct FPoseLink PassThroughSwimmingMovementAdditive, struct FPoseLink SwimmingMovementAdditiveLayerPose); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingMovementAdditiveLayerPose // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
	void SwimmingLayer(struct FPoseLink MainPlayerAnimBP, struct FPoseLink SwimmingLayer); // Function SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C.SwimmingLayer // (HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xda7c34
};

